@protocol= http
@domainname= localhost
@port= {{$dotenv PORT}}
@path=v1
@baseUrl = {{protocol}}://{{domainname}}:{{port}}/{{path}}

### GET /boardgames
GET {{baseUrl}}/boardgames



### GET /boardgames/:id
GET {{baseUrl}}/boardgames/6



### POST /boardgames
POST {{baseUrl}}/boardgames
Content-Type: application/json

{
    "name": "mord",
    "minAge": "8",
    "minPlayers": "2",
    "maxPlayers": "6",
    "type": "familial",
    "note": "4",
    "duration": {
        "hours":2,
        "minutes":40
    },
    "creator": "Anthony Pratt"
}



### PUT /boardgames/:id
PUT {{baseUrl}}/boardgames/13
Content-Type: application/json

{
    "name": "updateGam",
    "minAge":"4",
    "minPlayers": "2",
    "maxPlayers": "3",
    "type": "education",
    "note": "4",
    "duration": {
        "hours":1,
        "minutes":10
    },
    "creator": "Anthony Pratt"
}


### DELETE /boardgames/:id
DELETE {{baseUrl}}/boardgames/5


### PATCH /boardgames/:id
PATCH {{baseUrl}}/boardgames/13
Content-Type: application/json

{
    "id" :3,
    "name": "SEAB",
    "trompette":"caca",
    "minAge":"6"
    
}
